[package]
name = "resin"
version = "1.6.0"
description = "⚗️ Superfast CLI for the conventional commits commit format"
authors = ["Matt Gleich <email@mattglei.ch>"]
repository = "https://github.com/gleich/resin/"
homepage = "https://github.com/gleich/resin/"
license = "MPL-2.0"
edition = "2021"
keywords = ["cli", "commit", "git", "standardization"]

[dependencies]
anyhow = "1.0.47"
toml = "0.5.8"
serde = { version = "1.0.130", features = ["derive"] }
dialoguer = { version = "0.10.0", features = ["fuzzy-select"] }
colored = "2.0.0"
itertools = "0.10.1"
directories = "4.0.1"
configparser = "3.0.0"
clap = "3.1.0"
ctrlc = { version = "3.4.0", features = ["termination"] }
console = "0.15.7"
