[package]
name = "resin"
version = "1.3.1"
description = "⚗️ Superfast CLI interface for the conventional commits commit format"
authors = ["Matthew Gleich <email@mattglei.ch>"]
repository = "https://github.com/gleich/resin/"
homepage = "https://github.com/gleich/resin/"
license = "MPL-2.0"
edition = "2018"
keywords = ["cli", "commit", "git", "standardization"]

[dependencies]
anyhow = "1.0.40"
toml = "0.5.8"
serde = { version = "1.0.125", features = ["derive"] }
dialoguer = { version = "0.8.0", git = "https://github.com/mitsuhiko/dialoguer", features = [
    "fuzzy-select"
] }
colored = "2"
itertools = "0.10.0"
directories = "3.0.2"
configparser = "2.0.1"
clap = "2.33.3"
