[package]
name = "resin"
version = "0.1.0"
authors = ["Matthew Gleich <email@mattglei.ch>"]
repository = "https://github.com/Matt-Gleich/resin/"
homepage = "https://github.com/Matt-Gleich/resin/"
license = "MPL 2.0"
edition = "2018"
keywords = ["cli", "commit", "git", "standardization"]

[dependencies]
anyhow = "1.0.40"
toml = "0.5.8"
serde = { version = "1.0.125", features = ["derive"] }
dialoguer = "0.8.0"
colored = "2"
