[package]
name = "stabit"
version = "0.1.0"
authors = ["Matthew Gleich <email@mattglei.ch>"]
edition = "2018"

[dependencies]
anyhow = "1.0.40"
toml = "0.5.8"
serde = { version = "1.0.125", features = ["derive"] }
dialoguer = "0.8.0"
