[package]
name = "resin"
version = "1.2.2"
description = "⚗️ Superfast CLI interface for the conventional commits commit format"
authors = ["Matthew Gleich <email@mattglei.ch>"]
repository = "https://github.com/Matt-Gleich/resin/"
homepage = "https://github.com/Matt-Gleich/resin/"
license = "MPL-2.0"
edition = "2018"
keywords = ["cli", "commit", "git", "standardization"]

[dependencies]
anyhow = "1.0.40"
toml = "0.5.8"
serde = { version = "1.0.125", features = ["derive"] }
dialoguer = "0.8.0"
colored = "2"
itertools = "0.10.0"
directories = "3.0.2"
configparser = "2.0.1"
